language: cpp
sudo: false
cache:
  directories:
  - container
env:
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
- CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py | python /dev/stdin -d container -s setup/bii/setup.py -e bash -p /dev/stdout --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/bii/check.py ${COVERAGE} --cmake-namespace psq --generator "${CMAKE_GENERATOR}" --lint-exclude "*/cotire/*" --block "smspillaz/accelerate-target-cmake"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/bii/coverage.py
before_deploy:
- polysquare_run deploy/bii/deploy.py
deploy:
  provider: biicode
  skip_cleanup: true
  user:
    secure: L2hGYbQFbDVl31asKR8/zlaONJCNtpFZESXM2P5DVWS8vFB8Q7YKlGrjNkA+uj9sGSrn0TfL3GdHdHQPff8Bz6q0h/kXQSrUjawk7ejjcv7/x5cXEaRPfgV5/x0PjuuwmCLThDheiC2ThhwTerOUZyx79MHN57Cd4153wzzVew8=
  password:
    secure: Q+AGVH0G9tDGfhQu1362Fo9xk+PZWxpIKktL6IivOc9Np2i92L5Spx4/k28Iskq1F14azlaBTDJ4YNT4ASsu6eljmAF9U4uO0NfEjEKuzH8lTthXNgYJigfSdvN0gRD0Cr3+NEAxiyDgYX7uTC/oK90HtWSnLYXb3eCjsqQjW9Y=
  on:
    repo: polysquare/accelerate-target-cmake
    branch: master
    condition: ${DEPLOY} = 1